/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 09-abr.-2020 7:15:04 p. m. 				*/
/*  DBMS       : Oracle 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "Banco" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "Cliente" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "Corresponsal" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "Negociacion" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

/* Create Tables */

CREATE TABLE  "Banco"
(
	"id_banco" VARCHAR2(50) NOT NULL,
	"nombre" VARCHAR2(50) NULL,
	"id_correspnsal" VARCHAR2(50) NULL
)
;

CREATE TABLE  "Cliente"
(
	"id_cliente" VARCHAR2(50) NOT NULL,
	"numero_cuenta" VARCHAR2(50) NULL,
	"nombre_cliente" VARCHAR2(50) NULL,
	"apellido_cleinte" VARCHAR2(50) NULL,
	"id_correspnsal" VARCHAR2(50) NULL
)
;

CREATE TABLE  "Corresponsal"
(
	"id_correspnsal" VARCHAR2(50) NOT NULL,
	"nombre_correponsal" VARCHAR2(50) NULL,
	"nombre_banco_asociado" VARCHAR2(50) NULL
)
;

CREATE TABLE  "Negociacion"
(
	"id_retiro" VARCHAR2(50) NOT NULL,
	"fecha_hora" VARCHAR2(50) NULL,
	"origen" VARCHAR2(50) NULL,
	"destino" VARCHAR2(50) NULL,
	"id_correspnsal" VARCHAR2(50) NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks, Triggers */

ALTER TABLE  "Banco" 
 ADD CONSTRAINT "PK_Banco"
	PRIMARY KEY ("id_banco") 
 USING INDEX
;

CREATE INDEX "IXFK_Banco_Corresponsal"   
 ON  "Banco" ("id_correspnsal") 
;

ALTER TABLE  "Cliente" 
 ADD CONSTRAINT "PK_Table1"
	PRIMARY KEY ("id_cliente") 
 USING INDEX
;

CREATE INDEX "IXFK_Cliente_Corresponsal"   
 ON  "Cliente" ("id_correspnsal") 
;

ALTER TABLE  "Corresponsal" 
 ADD CONSTRAINT "PK_Corresponsal"
	PRIMARY KEY ("id_correspnsal") 
 USING INDEX
;

ALTER TABLE  "Negociacion" 
 ADD CONSTRAINT "PK_Table1"
	PRIMARY KEY ("id_retiro") 
 USING INDEX
;

CREATE INDEX "IXFK_Negociacion_Corresponsal"   
 ON  "Negociacion" ("id_correspnsal") 
;

/* Create Foreign Key Constraints */

ALTER TABLE  "Banco" 
 ADD CONSTRAINT "FK_Banco_Corresponsal"
	FOREIGN KEY ("id_correspnsal") REFERENCES  "Corresponsal" ("id_correspnsal")
;

ALTER TABLE  "Cliente" 
 ADD CONSTRAINT "FK_Cliente_Corresponsal"
	FOREIGN KEY ("id_correspnsal") REFERENCES  "Corresponsal" ("id_correspnsal")
;

ALTER TABLE  "Negociacion" 
 ADD CONSTRAINT "FK_Negociacion_Corresponsal"
	FOREIGN KEY ("id_correspnsal") REFERENCES  "Corresponsal" ("id_correspnsal")
;
